// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// transport_v3_profile_native_cpp
Rcpp::List transport_v3_profile_native_cpp(const arma::vec& reference_mass, const arma::vec& source_mass, const arma::mat& reference_relation, const arma::mat& source_relation, const arma::mat& spatial_cost, const arma::vec& coverage_values, const arma::vec& entropy_schedule, double temporal_weight, double selection_weight, int maxit, double step_size, double tolerance, int projection_maxit, double projection_tolerance);
RcppExport SEXP _eyesim_transport_v3_profile_native_cpp(SEXP reference_massSEXP, SEXP source_massSEXP, SEXP reference_relationSEXP, SEXP source_relationSEXP, SEXP spatial_costSEXP, SEXP coverage_valuesSEXP, SEXP entropy_scheduleSEXP, SEXP temporal_weightSEXP, SEXP selection_weightSEXP, SEXP maxitSEXP, SEXP step_sizeSEXP, SEXP toleranceSEXP, SEXP projection_maxitSEXP, SEXP projection_toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type reference_mass(reference_massSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type source_mass(source_massSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type reference_relation(reference_relationSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type source_relation(source_relationSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type spatial_cost(spatial_costSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type coverage_values(coverage_valuesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type entropy_schedule(entropy_scheduleSEXP);
    Rcpp::traits::input_parameter< double >::type temporal_weight(temporal_weightSEXP);
    Rcpp::traits::input_parameter< double >::type selection_weight(selection_weightSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type step_size(step_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< int >::type projection_maxit(projection_maxitSEXP);
    Rcpp::traits::input_parameter< double >::type projection_tolerance(projection_toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(transport_v3_profile_native_cpp(reference_mass, source_mass, reference_relation, source_relation, spatial_cost, coverage_values, entropy_schedule, temporal_weight, selection_weight, maxit, step_size, tolerance, projection_maxit, projection_tolerance));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_eyesim_transport_v3_profile_native_cpp", (DL_FUNC) &_eyesim_transport_v3_profile_native_cpp, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_eyesim(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
