# Directional probabilistic GazeWeave replay -------------------------------

validate_replay_probability_grid <- function(grid) {
  required <- c("background", "restart", "advance", "background_stay")
  if (!is.list(grid) || !identical(sort(names(grid)), sort(required))) {
    stop("transition_grid must contain background, restart, advance, and background_stay.")
  }
  valid <- vapply(grid, function(values) {
    is.numeric(values) && length(values) > 0L && all(is.finite(values)) &&
      all(values > 0 & values < 1)
  }, logical(1))
  if (!all(valid)) {
    stop("every transition grid must contain finite probabilities strictly between zero and one.")
  }
  combinations <- expand.grid(grid, KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
  if (any(combinations$background + combinations$restart >= 1)) {
    stop("background plus restart probability must be less than one.")
  }
  lapply(grid, as.numeric)
}

#' Specify the directional GazeWeave replay model
#'
#' Replay models a recall path as a sequence generated by local traversal of
#' encoding fixations, occasional chunk restarts, and a candidate-independent
#' background state. Under revision `"2026.10"` the hidden-Markov model
#' observes each recall fixation exactly once: its position and its duration.
#' Under `"2026.08"` it observes a normalized gaze-time grid. Transition and
#' emission parameters are selected using training trials only by
#' [fit_gaze_replay_model()].
#'
#' @param grid_size Revision `"2026.08"` only: the number of normalized
#'   duration-mass observations per recall trial. Revision `"2026.10"`
#'   ignores it (a one-time message says so when it is supplied), because
#'   the model observes each recall fixation once instead of a duration
#'   grid.
#' @param max_skip Maximum forward encoding-state jump in a local transition.
#' @param student_df Degrees of freedom for robust bivariate Student emissions.
#' @param scale_floor Positive lower bound for fitted spatial scales.
#' @param transition_grid Named list of candidate probabilities for background
#'   entry, chunk restart, local advance, and background persistence.
#' @param temperature_bounds Positive lower and upper bounds for training-only
#'   calibration of candidate likelihoods. Direct one-template fits retain
#'   temperature one because no contrastive calibration set exists.
#' @param reliability Response-blind reliability policy. `"none"` preserves
#'   the calibrated candidate posterior. `"effective_fixations"` learns a
#'   monotone shrinkage toward the declared candidate prior from the source
#'   path's duration-effective fixation count.
#' @param reliability_kappa_bounds Non-negative bounds for the reliability
#'   half-saturation parameter. The lower bound must be zero.
#' @param warp Cross-fitted warp specification.
#' @param screen Optional screen geometry. Under revision `"2026.10"` every
#'   emission density is truncated to and normalised over this rectangle.
#'   When it is `NULL`, emissions are normalised over the whole plane (a
#'   one-time message says so).
#' @param revision Model revision. `"2026.10"` (default) is a
#'   fixation-level HMM with one hidden-state visit per recall fixation. Each
#'   fixation emits a position and a duration. Positions follow
#'   screen-truncated Student densities for replay states and, for the
#'   background state, a participant-level screen-truncated kernel density of
#'   training recalls (excluding the candidate pool, see `background_by`)
#'   mixed with a uniform screen floor. Durations are log-normal, with
#'   log-duration mean `a + b * log(encoding duration)` for replay states and
#'   a separate log-normal for the background; these parameters are shared
#'   by every candidate. The score is the total trial log likelihood, so
#'   evidence grows with the number of recall fixations. The replay scale,
#'   duration parameters,
#'   background floor weight, and all transition probabilities are fitted by
#'   Baum-Welch (EM) on training rows, with `transition_grid` medians used
#'   only as starting values. `"2026.08"` reproduces the frozen behaviour:
#'   a duration grid of `grid_size` bins scored by mean log likelihood per
#'   bin, untruncated emissions, a single Student background at the training
#'   recall mean, a median nearest-neighbour replay scale, and grid search
#'   over `transition_grid`.
#' @param background_by Optional source-table columns (for example the
#'   participant identifier) defining the level at which the background
#'   density is estimated under revision `"2026.10"`. `NULL` pools all
#'   training recalls. Levels with fewer than three other training trials fall
#'   back to the pooled density; fitting reports this with a message and
#'   [gaze_replay_cv()] records the count in `provenance$background_fallback`.
#'   At scoring time the background excludes training rows whose
#'   exclusion key matches any candidate in the pool; it is never tied to
#'   the true candidate, so it does not depend on the label. The exclusion
#'   key is `setdiff(match_on, background_by)`. When `background_by` is not
#'   part of `match_on` (or is `NULL`), that key still contains the
#'   participant, so other participants' recalls of the candidate items stay
#'   in the background.
#' @param background_support Background evaluation protocol under revision
#'   `"2026.10"`. `"training"` (default) estimates every background from
#'   training recalls only: the `background_by` level when it has at least
#'   three training trials outside the candidate pool, otherwise the
#'   population (pooled) density. Under participant holdout every evaluation
#'   participant is unseen, so the population density is used and
#'   [gaze_replay_cv()] says so. `"held_out"` (opt-in, requires
#'   `background_by`) instead uses the evaluation participant's own recalls
#'   of items outside the scored row's candidate pool, available in the same
#'   evaluation fold, falling back to the training protocol when fewer than
#'   three such trials exist. It can engage only with an item-level split and
#'   a `contrast_on` that divides each participant's items into blocks, so
#'   that other-block recalls share the evaluation fold. Under participant
#'   holdout with shared items every item is a candidate, and it never
#'   engages. `"held_out"` is transductive: it reads the item labels of other
#'   evaluation rows to decide which recalls lie outside the pool, so it
#'   cannot be used on unlabelled recalls. Training fits always use the other
#'   training trials of the same level, excluding the fitted item.
#' @param calibration_control Revision `"2026.10"` only: a
#'   [gaze_calibration_control()]. `NULL` uses its defaults: an
#'   evidence-scaled temperature whose evidence count is the number of recall
#'   fixations, fitted on inner out-of-fold rows. `reliability =
#'   "effective_fixations"` then requires `method = "global"`.
#'
#' @return A frozen `gaze_replay_spec`.
#' @export
gaze_replay_spec <- function(
    grid_size = 64L,
    max_skip = 2L,
    student_df = 4,
    scale_floor = 0.05,
    transition_grid = list(
      background = c(0.02, 0.08),
      restart = c(0.01, 0.05, 0.12),
      advance = c(0.15, 0.35),
      background_stay = c(0.85, 0.95)
    ),
    temperature_bounds = c(0.05, 100),
    reliability = c("none", "effective_fixations"),
    reliability_kappa_bounds = c(0, 100),
    warp = gaze_warp_none(),
    screen = NULL,
    revision = c("2026.10", "2026.08"),
    background_by = NULL,
    background_support = c("training", "held_out"),
    calibration_control = NULL) {
  revision <- match.arg(revision)
  background_support <- match.arg(background_support)
  if (identical(background_support, "held_out") &&
      (identical(revision, "2026.08") || is.null(background_by))) {
    stop("background_support = \"held_out\" requires revision \"2026.10\" ",
         "and background_by.")
  }
  if (!is.null(background_by)) {
    if (identical(revision, "2026.08")) {
      stop("background_by requires revision = \"2026.10\".")
    }
    if (!is.character(background_by) || length(background_by) < 1L ||
        anyNA(background_by)) {
      stop("background_by must be NULL or a character vector of column names.")
    }
  }
  if (!missing(grid_size) && identical(revision, "2026.10")) {
    note_gaze_replay_grid_size()
  }
  grid_size <- as.integer(grid_size)
  max_skip <- as.integer(max_skip)
  if (length(grid_size) != 1L || is.na(grid_size) || grid_size < 4L) {
    stop("grid_size must be an integer of at least four.")
  }
  if (length(max_skip) != 1L || is.na(max_skip) || max_skip < 1L) {
    stop("max_skip must be a positive integer.")
  }
  if (!is.numeric(student_df) || length(student_df) != 1L ||
      !is.finite(student_df) || student_df <= 0) {
    stop("student_df must be a finite positive scalar.")
  }
  if (!is.numeric(scale_floor) || length(scale_floor) != 1L ||
      !is.finite(scale_floor) || scale_floor <= 0) {
    stop("scale_floor must be a finite positive scalar.")
  }
  if (!inherits(warp, "gaze_warp_spec")) {
    stop("warp must be created by gaze_warp_none() or gaze_warp_contraction().")
  }
  if (!is.numeric(temperature_bounds) || length(temperature_bounds) != 2L ||
      any(!is.finite(temperature_bounds)) || any(temperature_bounds <= 0) ||
      temperature_bounds[[1]] >= temperature_bounds[[2]]) {
    stop("temperature_bounds must contain increasing finite positive values.")
  }
  reliability <- match.arg(reliability)
  if (!is.numeric(reliability_kappa_bounds) ||
      length(reliability_kappa_bounds) != 2L ||
      any(!is.finite(reliability_kappa_bounds)) ||
      reliability_kappa_bounds[[1L]] != 0 ||
      reliability_kappa_bounds[[2L]] <= 0) {
    stop("reliability_kappa_bounds must run from zero to a finite positive value.")
  }
  if (!is.null(screen) && !inherits(screen, "gaze_screen")) {
    stop("screen must be NULL or created by gaze_screen().")
  }
  if (identical(warp$type, "contraction") &&
      is.character(warp$center) && is.null(screen)) {
    stop("gaze_warp_contraction(center = 'screen') requires a screen specification.")
  }
  calibration_control <- resolve_gaze_calibration_control(
    calibration_control, revision, reliability, "replay"
  )
  calibration <- list(
    folds = 2L,
    seed = 104729L,
    log_temperature_prior_sd = 1,
    log1p_kappa_prior_sd = 1
  )
  # Frozen revision 2026.08 specifications carry no calibration control.
  if (!is.null(calibration_control)) calibration$control <- calibration_control

  structure(
    list(
      grid_size = grid_size,
      max_skip = max_skip,
      student_df = as.numeric(student_df),
      scale_floor = as.numeric(scale_floor),
      transition_grid = validate_replay_probability_grid(transition_grid),
      temperature_bounds = as.numeric(temperature_bounds),
      reliability = reliability,
      reliability_kappa_bounds = as.numeric(reliability_kappa_bounds),
      warp = warp,
      screen = screen,
      chronology = gaze_local_order(),
      calibration = calibration,
      version = if (identical(revision, "2026.08")) 3L else 4L,
      revision = revision,
      background_by = background_by,
      background_support = if (identical(revision, "2026.08")) NULL else
        background_support
    ),
    class = c("gaze_replay_spec", "list")
  )
}

gaze_duration_grid <- function(measure, grid_size) {
  if (!inherits(measure, "gaze_measure")) {
    stop("measure must be a gaze_measure.")
  }
  points <- (seq_len(grid_size) - 0.5) / grid_size
  boundaries <- c(0, cumsum(measure$mass))
  index <- findInterval(points, boundaries, all.inside = TRUE)
  index <- pmin(index, nrow(measure$coords))
  list(
    coords = measure$coords[index, , drop = FALSE],
    fixation_index = index,
    time = points,
    grid_size = grid_size
  )
}

gaze_replay_mean_log_score <- function(log_likelihood, grid_size) {
  if (!is.numeric(log_likelihood) || length(log_likelihood) != 1L ||
      is.na(log_likelihood) || log_likelihood == Inf) {
    stop("log_likelihood must be one numeric value other than NA or Inf.")
  }
  grid_size <- as.integer(grid_size)
  if (length(grid_size) != 1L || is.na(grid_size) || grid_size < 1L) {
    stop("grid_size must be a positive integer.")
  }
  log_likelihood / grid_size
}

gaze_replay_log_mixture <- function(log_score, weights = NULL) {
  if (!is.numeric(log_score) || length(log_score) < 1L || anyNA(log_score) ||
      any(log_score == Inf) || !any(is.finite(log_score))) {
    stop("log_score must contain at least one finite value and no NA or Inf.")
  }
  if (is.null(weights)) weights <- rep(1 / length(log_score), length(log_score))
  if (!is.numeric(weights) || length(weights) != length(log_score) ||
      any(!is.finite(weights)) || any(weights <= 0) || sum(weights) <= 0) {
    stop("weights must contain one finite positive value per template.")
  }
  weights <- weights / sum(weights)
  log_weight <- log(weights) + log_score
  mixture <- gaze_log_sum_exp(log_weight)
  posterior_weight <- exp(log_weight - mixture)
  posterior_weight <- posterior_weight / sum(posterior_weight)
  list(
    log_score = mixture,
    prior_weight = weights,
    posterior_weight = posterior_weight
  )
}

gaze_replay_path_quality <- function(path) {
  measure <- as_gaze_measure(path, gaze_local_order())
  fixations <- measure$fixations
  coalesced <- coalesce_adjacent_gaze_fixations(
    fixations, distance = 0, kept_index = seq_len(nrow(fixations))
  )$fixations
  mass <- coalesced$duration / sum(coalesced$duration)
  center <- c(
    sum(coalesced$x * mass),
    sum(coalesced$y * mass)
  )
  radius_sq <- (coalesced$x - center[[1L]])^2 +
    (coalesced$y - center[[2L]])^2
  concentration <- sum(mass^2)
  list(
    raw_fixation_count = as.integer(nrow(fixations)),
    coalesced_fixation_count = as.integer(nrow(coalesced)),
    effective_fixations = as.numeric(1 / concentration),
    total_duration = as.numeric(sum(coalesced$duration)),
    duration_concentration = as.numeric(concentration),
    spatial_dispersion = as.numeric(sqrt(sum(mass * radius_sq)))
  )
}

gaze_replay_reliability <- function(effective_fixations, kappa) {
  if (!is.numeric(effective_fixations) || length(effective_fixations) < 1L ||
      any(!is.finite(effective_fixations)) || any(effective_fixations <= 0)) {
    stop("effective_fixations must contain finite positive values.")
  }
  if (!is.numeric(kappa) || length(kappa) != 1L || !is.finite(kappa) ||
      kappa < 0) {
    stop("kappa must be one finite non-negative value.")
  }
  as.numeric(effective_fixations / (effective_fixations + kappa))
}

gaze_replay_reliability_loss <- function(
    temperature, kappa, score_sets, true_index, prior_sets,
    effective_fixations) {
  reliability <- gaze_replay_reliability(effective_fixations, kappa)
  losses <- vapply(seq_along(score_sets), function(i) {
    base <- gaze_candidate_probabilities(
      score_sets[[i]], prior_sets[[i]], temperature
    )
    posterior <- reliability[[i]] * base +
      (1 - reliability[[i]]) * prior_sets[[i]]
    -log(posterior[[true_index[[i]]]])
  }, numeric(1))
  mean(losses)
}

gaze_replay_calibration_parameters <- function(parameter, lower, upper) {
  if (!is.numeric(parameter) || length(parameter) != 2L ||
      any(!is.finite(parameter))) {
    return(NULL)
  }
  bounded <- pmax(lower, pmin(upper, parameter))
  temperature <- exp(bounded[[1L]])
  kappa <- max(0, expm1(bounded[[2L]]))
  if (!is.finite(temperature) || temperature <= 0 ||
      !is.finite(kappa)) {
    return(NULL)
  }
  list(
    temperature = temperature,
    kappa = kappa,
    parameter = bounded
  )
}

fit_gaze_replay_reliability <- function(
    log_scores, true_index, effective_fixations, prior = NULL,
    temperature_bounds = c(0.05, 20), kappa_bounds = c(0, 100),
    log_temperature_prior_sd = 1, log1p_kappa_prior_sd = 1) {
  score_sets <- as_gaze_score_sets(log_scores)
  true_index <- validate_gaze_truth(true_index, score_sets)
  prior_sets <- as_gaze_prior_sets(prior, score_sets)
  if (!is.numeric(effective_fixations) ||
      length(effective_fixations) != length(score_sets) ||
      any(!is.finite(effective_fixations)) || any(effective_fixations <= 0)) {
    stop("effective_fixations must provide one finite positive value per score set.")
  }
  if (!is.numeric(kappa_bounds) || length(kappa_bounds) != 2L ||
      any(!is.finite(kappa_bounds)) || kappa_bounds[[1L]] != 0 ||
      kappa_bounds[[2L]] <= 0) {
    stop("kappa_bounds must run from zero to a finite positive value.")
  }
  if (!is.numeric(log1p_kappa_prior_sd) ||
      length(log1p_kappa_prior_sd) != 1L ||
      is.na(log1p_kappa_prior_sd) || log1p_kappa_prior_sd <= 0) {
    stop("log1p_kappa_prior_sd must be one positive scalar.")
  }
  temperature_only <- fit_gaze_temperature(
    score_sets, true_index, prior_sets, bounds = temperature_bounds,
    log_temperature_prior_sd = log_temperature_prior_sd
  )
  sample_n <- length(score_sets)
  temperature_penalty <- if (is.infinite(log_temperature_prior_sd)) {
    0
  } else {
    1 / (2 * sample_n * log_temperature_prior_sd^2)
  }
  kappa_penalty <- if (is.infinite(log1p_kappa_prior_sd)) {
    0
  } else {
    1 / (2 * sample_n * log1p_kappa_prior_sd^2)
  }
  lower <- c(log(temperature_bounds[[1L]]), 0)
  upper <- c(
    log(temperature_bounds[[2L]]), log1p(kappa_bounds[[2L]])
  )
  objective <- function(parameter) {
    values <- gaze_replay_calibration_parameters(parameter, lower, upper)
    if (is.null(values)) return(.Machine$double.xmax / 100)
    loss <- gaze_replay_reliability_loss(
      values$temperature, values$kappa,
      score_sets, true_index, prior_sets, effective_fixations
    ) + temperature_penalty * values$parameter[[1L]]^2 +
      kappa_penalty * values$parameter[[2L]]^2
    if (is.finite(loss)) loss else .Machine$double.xmax / 100
  }
  starts <- rbind(
    c(log(temperature_only$temperature), 0),
    c(log(temperature_only$temperature), log1p(kappa_bounds[[2L]]) / 2),
    c(0, log1p(kappa_bounds[[2L]]) / 4)
  )
  fits <- lapply(seq_len(nrow(starts)), function(i) {
    tryCatch(
      stats::optim(
        starts[i, ], objective, method = "L-BFGS-B",
        lower = lower, upper = upper
      ),
      error = function(error) list(
        par = starts[i, ], value = objective(starts[i, ]),
        convergence = 999L, message = conditionMessage(error)
      )
    )
  })
  fit_value <- vapply(fits, function(value) {
    if (is.null(value$value) || !is.finite(value$value)) Inf else value$value
  }, numeric(1))
  fitted <- fits[[which.min(fit_value)]]
  fitted_parameters <- gaze_replay_calibration_parameters(
    fitted$par, lower, upper
  )
  if (is.null(fitted_parameters)) {
    fitted_parameters <- list(
      temperature = temperature_only$temperature,
      kappa = 0
    )
  }
  temperature <- fitted_parameters$temperature
  kappa <- fitted_parameters$kappa
  loss <- gaze_replay_reliability_loss(
    temperature, kappa, score_sets, true_index, prior_sets,
    effective_fixations
  )
  if (loss > temperature_only$log_loss + 1e-10) {
    temperature <- temperature_only$temperature
    kappa <- 0
    loss <- temperature_only$log_loss
  }
  tolerance <- 1e-4
  structure(
    list(
      temperature = as.numeric(temperature),
      kappa = as.numeric(kappa),
      log_loss = as.numeric(loss),
      temperature_only_temperature = temperature_only$temperature,
      temperature_only_log_loss = temperature_only$log_loss,
      uncalibrated_log_loss = gaze_replay_reliability_loss(
        1, 0, score_sets, true_index, prior_sets, effective_fixations
      ),
      penalized_objective = fitted$value,
      training_n = sample_n,
      temperature_bounds = as.numeric(temperature_bounds),
      kappa_bounds = as.numeric(kappa_bounds),
      at_temperature_boundary = any(
        abs(log(temperature) - log(temperature_bounds)) <= tolerance
      ),
      at_kappa_boundary = any(
        abs(kappa - kappa_bounds) <= tolerance *
          max(1, diff(kappa_bounds))
      ),
      scheme = "joint_temperature_effective_fixation_shrinkage"
    ),
    class = c("gaze_reliability_fit", "list")
  )
}

gaze_bivariate_t_log_density <- function(observed, center, scale, degrees) {
  if (!is.matrix(observed) || ncol(observed) != 2L ||
      !is.numeric(center) || length(center) != 2L ||
      !is.numeric(scale) || length(scale) != 1L || scale <= 0) {
    stop("Invalid bivariate Student emission parameters.")
  }
  centered <- sweep(observed, 2, center, FUN = "-")
  radius_sq <- rowSums(centered^2)
  lgamma((degrees + 2) / 2) - lgamma(degrees / 2) -
    log(degrees * pi) - 2 * log(scale) -
    ((degrees + 2) / 2) * log1p(radius_sq / (degrees * scale^2))
}

gaze_replay_transition <- function(reference_mass, parameters, max_skip) {
  n_reference <- length(reference_mass)
  n_states <- n_reference + 1L
  background <- parameters$background
  restart <- parameters$restart
  advance <- parameters$advance
  background_stay <- parameters$background_stay
  if (background + restart >= 1) {
    stop("Replay background and restart probabilities must sum to less than one.")
  }

  transition <- matrix(0, n_states, n_states)
  restart_component <- matrix(0, n_states, n_states)
  local_component <- matrix(0, n_states, n_states)
  transition[1, 1] <- background_stay
  transition[1, -1] <- (1 - background_stay) * reference_mass

  for (i in seq_len(n_reference)) {
    row <- i + 1L
    transition[row, 1] <- background
    restart_values <- restart * reference_mass
    restart_component[row, -1] <- restart_values

    local_mass <- 1 - background - restart
    successors <- if (i < n_reference) {
      seq.int(i + 1L, min(n_reference, i + max_skip))
    } else {
      integer()
    }
    if (length(successors) == 0L) {
      local_component[row, i + 1L] <- local_mass
    } else {
      local_component[row, i + 1L] <- local_mass * (1 - advance)
      lag <- successors - i
      weights <- 0.5^(lag - 1L)
      weights <- weights / sum(weights)
      local_component[row, successors + 1L] <- local_mass * advance * weights
    }
    transition[row, -1] <- restart_values + local_component[row, -1]
  }

  initial <- c(background, (1 - background) * reference_mass)
  if (any(abs(rowSums(transition) - 1) > 1e-12) ||
      abs(sum(initial) - 1) > 1e-12) {
    stop("Internal replay transition construction failed to normalize.")
  }
  restart_responsibility <- matrix(0, n_states, n_states)
  positive <- transition > 0
  restart_responsibility[positive] <-
    restart_component[positive] / transition[positive]

  list(
    transition = transition,
    initial = initial,
    restart_component = restart_component,
    local_component = local_component,
    restart_responsibility = restart_responsibility,
    reference_mass = reference_mass,
    parameters = parameters,
    max_skip = max_skip
  )
}

gaze_replay_emissions <- function(reference, grid, emission_model, degrees) {
  if (identical(emission_model$revision, "2026.10")) {
    return(gaze_replay_emissions_revision(
      reference, grid, emission_model, degrees
    ))
  }
  n_reference <- nrow(reference$coords)
  log_emission <- matrix(NA_real_, nrow(grid$coords), n_reference + 1L)
  log_emission[, 1] <- gaze_bivariate_t_log_density(
    grid$coords,
    emission_model$background_center,
    emission_model$background_scale,
    degrees
  )
  for (i in seq_len(n_reference)) {
    log_emission[, i + 1L] <- gaze_bivariate_t_log_density(
      grid$coords,
      reference$coords[i, ],
      emission_model$replay_scale,
      degrees
    )
  }
  log_emission
}

gaze_hmm_forward_backward <- function(log_emission, initial, transition) {
  n_time <- nrow(log_emission)
  n_states <- ncol(log_emission)
  if (length(initial) != n_states || any(dim(transition) != c(n_states, n_states)) ||
      any(initial < 0) || any(transition < 0) ||
      abs(sum(initial) - 1) > 1e-10 ||
      any(abs(rowSums(transition) - 1) > 1e-10)) {
    stop("Initial and transition probabilities do not match the emissions.")
  }
  log_initial <- log(initial)
  log_transition <- log(transition)
  forward <- matrix(-Inf, n_time, n_states)
  forward[1, ] <- log_initial + log_emission[1, ]
  if (n_time > 1L) {
    for (time in 2:n_time) {
      for (state in seq_len(n_states)) {
        forward[time, state] <- log_emission[time, state] +
          gaze_log_sum_exp(forward[time - 1L, ] + log_transition[, state])
      }
    }
  }
  log_likelihood <- gaze_log_sum_exp(forward[n_time, ])

  backward <- matrix(0, n_time, n_states)
  if (n_time > 1L) {
    for (time in seq.int(n_time - 1L, 1L)) {
      for (state in seq_len(n_states)) {
        backward[time, state] <- gaze_log_sum_exp(
          log_transition[state, ] + log_emission[time + 1L, ] +
            backward[time + 1L, ]
        )
      }
    }
  }
  log_posterior <- forward + backward - log_likelihood
  posterior <- exp(log_posterior)
  posterior <- posterior / rowSums(posterior)

  transition_posterior <- array(0, dim = c(max(n_time - 1L, 0L), n_states, n_states))
  if (n_time > 1L) {
    for (time in seq_len(n_time - 1L)) {
      log_xi <- outer(
        forward[time, ],
        log_emission[time + 1L, ] + backward[time + 1L, ],
        FUN = "+"
      ) + log_transition - log_likelihood
      xi <- exp(log_xi)
      transition_posterior[time, , ] <- xi / sum(xi)
    }
  }

  list(
    log_likelihood = log_likelihood,
    forward = forward,
    backward = backward,
    posterior = posterior,
    transition_posterior = transition_posterior
  )
}

# Row-scaled emissions: they depend only on the emissions, not on the
# transition, so a transition grid search computes them once per pair.
gaze_replay_scale_emissions <- function(log_emission) {
  emission_max <- apply(log_emission, 1, max)
  list(
    max = emission_max,
    scaled = exp(sweep(log_emission, 1, emission_max, FUN = "-"))
  )
}

# Scaled forward pass; its log likelihood is the full-data log likelihood.
gaze_replay_forward <- function(emission, replay_transition) {
  emission_max <- emission$max
  emission_scaled <- emission$scaled
  n_time <- nrow(emission_scaled)
  n_states <- ncol(emission_scaled)
  n_reference <- n_states - 1L
  reference_mass <- replay_transition$reference_mass
  parameters <- replay_transition$parameters
  local <- replay_transition$local_component[-1, -1, drop = FALSE]
  if (length(reference_mass) != n_reference ||
      any(dim(local) != c(n_reference, n_reference))) {
    stop("Replay transition decomposition does not match the emissions.")
  }

  forward <- matrix(0, n_time, n_states)
  scale <- numeric(n_time)

  unnormalized <- replay_transition$initial * emission_scaled[1, ]
  scale[[1]] <- sum(unnormalized)
  forward[1, ] <- unnormalized / scale[[1]]
  log_likelihood <- emission_max[[1]] + log(scale[[1]])

  if (n_time > 1L) {
    for (time in 2:n_time) {
      previous_background <- forward[time - 1L, 1]
      previous_replay <- forward[time - 1L, -1]
      predicted <- numeric(n_states)
      predicted[[1]] <- parameters$background_stay * previous_background +
        parameters$background * sum(previous_replay)
      restart_in <- (1 - parameters$background_stay) * previous_background +
        parameters$restart * sum(previous_replay)
      predicted[-1] <- reference_mass * restart_in +
        as.numeric(previous_replay %*% local)
      unnormalized <- predicted * emission_scaled[time, ]
      scale[[time]] <- sum(unnormalized)
      forward[time, ] <- unnormalized / scale[[time]]
      log_likelihood <- log_likelihood + emission_max[[time]] + log(scale[[time]])
    }
  }

  list(
    log_likelihood = log_likelihood,
    forward = forward,
    scaling = scale,
    emission_scaled = emission_scaled,
    reference_mass = reference_mass,
    parameters = parameters,
    local = local
  )
}

gaze_replay_forward_backward <- function(log_emission, replay_transition) {
  pass <- gaze_replay_forward(
    gaze_replay_scale_emissions(log_emission), replay_transition
  )
  n_time <- nrow(log_emission)
  n_states <- ncol(log_emission)
  forward <- pass$forward
  scale <- pass$scaling
  log_likelihood <- pass$log_likelihood
  emission_scaled <- pass$emission_scaled
  reference_mass <- pass$reference_mass
  parameters <- pass$parameters
  local <- pass$local

  backward <- matrix(1, n_time, n_states)
  expected_restart <- numeric(max(n_time - 1L, 0L))
  if (n_time > 1L) {
    for (time in seq.int(n_time - 1L, 1L)) {
      weighted_next <- emission_scaled[time + 1L, ] * backward[time + 1L, ]
      weighted_background <- weighted_next[[1]]
      weighted_replay <- weighted_next[-1]
      restart_target <- sum(reference_mass * weighted_replay)
      backward[time, 1] <- (
        parameters$background_stay * weighted_background +
          (1 - parameters$background_stay) * restart_target
      ) / scale[[time + 1L]]
      backward[time, -1] <- (
        parameters$background * weighted_background +
          parameters$restart * restart_target +
          as.numeric(local %*% weighted_replay)
      ) / scale[[time + 1L]]
      expected_restart[[time]] <-
        sum(forward[time, -1]) * parameters$restart * restart_target /
        scale[[time + 1L]]
    }
  }

  posterior <- forward * backward
  posterior <- posterior / rowSums(posterior)
  list(
    log_likelihood = log_likelihood,
    forward = forward,
    backward = backward,
    posterior = posterior,
    expected_restart = expected_restart,
    scaling = scale,
    complexity = "O(duration_grid * encoding_fixations * max_skip)"
  )
}

fit_gaze_replay_emission <- function(pairs, grid_size, scale_floor) {
  source_coords <- do.call(rbind, lapply(pairs, function(pair) {
    gaze_duration_grid(pair$source, grid_size)$coords
  }))
  background_center <- colMeans(source_coords)
  centered <- sweep(source_coords, 2, background_center, FUN = "-")
  background_scale <- max(sqrt(mean(rowSums(centered^2)) / 2), 2 * scale_floor)

  nearest_distance <- unlist(lapply(pairs, function(pair) {
    source <- gaze_duration_grid(pair$source, grid_size)$coords
    dx <- outer(source[, 1], pair$reference$coords[, 1], FUN = "-")
    dy <- outer(source[, 2], pair$reference$coords[, 2], FUN = "-")
    sqrt(apply(dx^2 + dy^2, 1, min))
  }), use.names = FALSE)
  replay_scale <- max(stats::median(nearest_distance), scale_floor)

  list(
    background_center = as.numeric(background_center),
    background_scale = background_scale,
    replay_scale = replay_scale,
    training_grid_points = nrow(source_coords)
  )
}

# The duration grid and emissions of a pair do not depend on the transition
# parameters, so the transition grid search prepares them once per pair.
gaze_replay_pair_emissions <- function(reference, registered_source,
                                       emission_model, spec, grid = NULL) {
  if (is.null(grid)) {
    grid <- gaze_duration_grid(registered_source, spec$grid_size)
  }
  list(
    grid = grid,
    log_emission = gaze_replay_emissions(
      reference, grid, emission_model, spec$student_df
    )
  )
}

gaze_replay_pair_alignment <- function(reference, registered_source,
                                       emission_model, parameters, spec,
                                       grid = NULL) {
  prepared <- gaze_replay_pair_emissions(
    reference, registered_source, emission_model, spec, grid
  )
  grid <- prepared$grid
  log_emission <- prepared$log_emission
  transition <- gaze_replay_transition(reference$mass, parameters, spec$max_skip)
  fit <- gaze_replay_forward_backward(log_emission, transition)

  replay_posterior <- fit$posterior[, -1, drop = FALSE]
  replay_probability <- rowSums(replay_posterior)
  normalized_replay <- replay_posterior
  positive <- replay_probability > 0
  normalized_replay[positive, ] <-
    replay_posterior[positive, , drop = FALSE] / replay_probability[positive]
  barycentric <- normalized_replay %*% reference$coords
  barycentric[!positive, ] <- NA_real_

  dx <- outer(grid$coords[, 1], reference$coords[, 1], FUN = "-")
  dy <- outer(grid$coords[, 2], reference$coords[, 2], FUN = "-")
  replay_weight <- sum(replay_posterior)
  spatial_rmse <- if (replay_weight > 0) {
    sqrt(sum(replay_posterior * (dx^2 + dy^2)) / replay_weight)
  } else {
    NA_real_
  }
  expected_restart <- sum(fit$expected_restart)

  structure(
    list(
      log_likelihood = fit$log_likelihood,
      mean_log_score = gaze_replay_mean_log_score(
        fit$log_likelihood, spec$grid_size
      ),
      posterior = fit$posterior,
      replay_posterior = replay_posterior,
      grid = grid,
      barycentric = barycentric,
      transition = transition,
      emissions = log_emission,
      diagnostics = list(
        replay_coverage = mean(replay_probability),
        background_coverage = mean(fit$posterior[, 1]),
        encoding_visitation = colMeans(replay_posterior),
        expected_restarts = expected_restart,
        restart_rate = if (spec$grid_size > 1L) {
          expected_restart / (spec$grid_size - 1L)
        } else {
          NA_real_
        },
        spatial_rmse = spatial_rmse,
        template_state_count = nrow(reference$coords),
        grid_size = spec$grid_size
      ),
      convergence = list(
        converged = is.finite(fit$log_likelihood) && all(is.finite(fit$posterior)),
        method = "scaled_low_rank_forward_backward",
        complexity = fit$complexity
      )
    ),
    class = c("gaze_replay_alignment", "list")
  )
}

replay_group_keys <- function(source_tab, fit_by) {
  if (is.null(fit_by)) rep("all", nrow(source_tab)) else
    gaze_key(source_tab, fit_by, "warp fit_by")
}

replay_template_labels <- function(tab, template_on) {
  if (length(template_on) == 1L) {
    return(as.character(tab[[template_on]]))
  }
  gaze_key(tab, template_on, "template_on")
}

replay_template_structure <- function(ref_tab, source_tab, match_on,
                                      template_on = NULL) {
  ref_key <- gaze_key(ref_tab, match_on, "match_on")
  source_key <- gaze_key(source_tab, match_on, "match_on")
  if (is.null(template_on)) {
    if (anyDuplicated(ref_key)) {
      stop("Reference match_on keys must be unique unless template_on is declared.")
    }
    template_key <- rep("template", nrow(ref_tab))
  } else {
    if (!is.character(template_on) || length(template_on) < 1L ||
        !all(template_on %in% names(ref_tab))) {
      stop("template_on must name one or more reference columns.")
    }
    combined_key <- gaze_key(
      ref_tab, unique(c(match_on, template_on)),
      "combined match_on and template_on"
    )
    if (anyDuplicated(combined_key)) {
      stop("Every match_on and template_on combination must be unique.")
    }
    template_key <- replay_template_labels(ref_tab, template_on)
  }
  rows_by_key <- split(seq_len(nrow(ref_tab)), ref_key)
  source_rows <- lapply(source_key, function(key) {
    rows <- rows_by_key[[key]]
    if (is.null(rows) || !length(rows)) integer() else
      rows[order(template_key[rows])]
  })
  if (any(lengths(source_rows) < 1L)) {
    stop("Every Replay training source path must have a reference match.")
  }
  list(
    ref_key = ref_key,
    source_key = source_key,
    template_key = template_key,
    source_rows = source_rows,
    template_on = template_on
  )
}

fit_gaze_replay_warp <- function(ref_tab, source_tab, structure,
                                 match_on, refvar, sourcevar, spec) {
  if (is.null(structure$template_on)) {
    return(fit_gaze_warp_model(
      ref_tab, source_tab, match_on, refvar, sourcevar, spec
    ))
  }
  source_rows <- rep(
    seq_len(nrow(source_tab)), lengths(structure$source_rows)
  )
  reference_rows <- unlist(structure$source_rows, use.names = FALSE)
  expanded_reference <- ref_tab[reference_rows, , drop = FALSE]
  expanded_source <- source_tab[source_rows, , drop = FALSE]
  pair_id <- paste0("episode-pair-", seq_along(source_rows))
  expanded_reference[["..replay_episode_pair"]] <- pair_id
  expanded_source[["..replay_episode_pair"]] <- pair_id
  fit_gaze_warp_model(
    expanded_reference, expanded_source,
    match_on = "..replay_episode_pair",
    refvar = refvar, sourcevar = sourcevar, spec = spec
  )
}

#' Fit a directional GazeWeave replay model on training trials
#'
#' The fitted warp, background distribution, emission scale, and transition
#' parameters are learned from the supplied matched training trials. When
#' `contrast_on` is supplied, the likelihood temperature is learned from
#' inner-held-out item scores with a fixed weak log-temperature prior. Scored
#' trials must be disjoint from all of these rows. Training strata too small
#' for two candidate-bearing inner folds retain temperature one and record the
#' fallback in `model$calibration`.
#'
#' @param ref_tab,source_tab Matched training reference and source tables.
#' @param match_on Columns defining matched paths.
#' @param contrast_on Optional columns defining training candidate sets for
#'   likelihood-temperature calibration.
#' @param refvar,sourcevar Fixation-group list columns.
#' @param spec A [gaze_replay_spec()].
#' @param template_on Optional columns that uniquely identify separate encoding
#'   presentations within each `match_on` episode. Their likelihoods are
#'   combined with equal prior weight; paths are never concatenated.
#'
#' @return A fitted `gaze_replay_model`.
#' @export
fit_gaze_replay_model <- function(ref_tab, source_tab, match_on,
                                  contrast_on = NULL,
                                  refvar = "fixgroup", sourcevar = "fixgroup",
                                  spec = gaze_replay_spec(),
                                  template_on = NULL) {
  if (!inherits(spec, "gaze_replay_spec")) {
    stop("spec must be created by gaze_replay_spec().")
  }
  if (!refvar %in% names(ref_tab) || !sourcevar %in% names(source_tab) ||
      nrow(source_tab) == 0L) {
    stop("Training tables must contain non-empty fixation-group list columns.")
  }
  templates <- replay_template_structure(
    ref_tab, source_tab, match_on, template_on
  )
  ref_key <- templates$ref_key
  source_key <- templates$source_key

  warp <- fit_gaze_replay_warp(
    ref_tab, source_tab, templates, match_on, refvar, sourcevar, spec
  )
  group_key <- replay_group_keys(source_tab, spec$warp$fit_by)
  episodes <- lapply(seq_len(nrow(source_tab)), function(i) {
    group_warp <- if (identical(warp$type, "none")) {
      warp
    } else {
      subset_gaze_warp_model(warp, group_key[[i]])
    }
    source <- as_gaze_measure(source_tab[[sourcevar]][[i]], spec$chronology)
    list(
      references = lapply(
        ref_tab[[refvar]][templates$source_rows[[i]]],
        as_gaze_measure, chronology = spec$chronology
      ),
      template_key = templates$template_key[templates$source_rows[[i]]],
      source = apply_gaze_warp_model(source, group_warp),
      group = group_key[[i]]
    )
  })
  pairs <- unlist(lapply(episodes, function(episode) {
    lapply(episode$references, function(reference) {
      list(
        reference = reference,
        source = episode$source,
        group = episode$group
      )
    })
  }), recursive = FALSE)

  legacy <- gaze_replay_is_legacy(spec)
  evidence_scaled <- !legacy && gaze_calibration_evidence_scaled(spec)
  typicality <- !legacy && gaze_calibration_typicality(spec)
  revision_fit <- NULL
  if (legacy) {
    emission_models <- lapply(sort(unique(group_key)), function(group) {
      fit_gaze_replay_emission(
        pairs[vapply(pairs, `[[`, character(1), "group") == group],
        spec$grid_size,
        spec$scale_floor
      )
    })
    names(emission_models) <- sort(unique(group_key))

    candidates <- expand.grid(
      spec$transition_grid,
      KEEP.OUT.ATTRS = FALSE,
      stringsAsFactors = FALSE
    )
    # Emissions do not depend on the transition candidate, and the mean log
    # score needs only the forward pass: prepare the emissions once per pair.
    episode_emissions <- lapply(episodes, function(episode) {
      grid <- gaze_duration_grid(episode$source, spec$grid_size)
      lapply(episode$references, function(reference) {
        gaze_replay_scale_emissions(gaze_replay_pair_emissions(
          reference,
          episode$source,
          emission_models[[episode$group]],
          spec,
          grid = grid
        )$log_emission)
      })
    })
    candidate_log_likelihood <- vapply(seq_len(nrow(candidates)), function(index) {
      parameters <- as.list(candidates[index, , drop = FALSE])
      sum(vapply(seq_along(episodes), function(e) {
        references <- episodes[[e]]$references
        component_score <- vapply(seq_along(references), function(r) {
          transition <- gaze_replay_transition(
            references[[r]]$mass, parameters, spec$max_skip
          )
          gaze_replay_mean_log_score(
            gaze_replay_forward(
              episode_emissions[[e]][[r]], transition
            )$log_likelihood,
            spec$grid_size
          )
        }, numeric(1))
        gaze_replay_log_mixture(component_score)$log_score
      }, numeric(1)))
    }, numeric(1))
    best <- which.max(candidate_log_likelihood)
    parameters <- as.list(candidates[best, , drop = FALSE])
  } else {
    revision_fit <- fit_gaze_replay_revision(
      episodes, source_tab, match_on, spec, group_key
    )
    emission_models <- revision_fit$emission_models
    parameters <- revision_fit$parameters
    candidates <- NULL
    candidate_log_likelihood <- NULL
    best <- NA_integer_
  }

  calibration <- NULL
  temperature <- 1
  reliability_kappa <- 0
  score_scale <- if (legacy) {
    "mean_log_likelihood_per_duration_bin"
  } else {
    "total_trial_log_likelihood"
  }
  if (!is.null(contrast_on)) {
    if (!all(contrast_on %in% names(ref_tab)) ||
        !all(contrast_on %in% names(source_tab))) {
      stop("Replay contrast_on columns must exist in both training tables.")
    }
    source_contrast <- gaze_key(source_tab, contrast_on, "contrast_on")
    # Inner folds split on match_on, so count distinct items, not rows.
    groups_per_stratum <- tapply(
      source_key, source_contrast, function(key) length(unique(key))
    )
    calibration_folds <- spec$calibration$folds
    enough_for_inner_candidates <- all(
      groups_per_stratum >= 2L * calibration_folds
    )

    if (enough_for_inner_candidates) {
      inner <- make_gaze_weave_folds(
        source_tab,
        split_on = match_on,
        contrast_on = contrast_on,
        n_folds = calibration_folds,
        seed = spec$calibration$seed
      )
      score_sets <- vector("list", nrow(source_tab))
      true_index <- integer(nrow(source_tab))
      evidence_count <- numeric(nrow(source_tab))
      typicality_tables <- list()
      fold_audit <- vector("list", inner$n_folds)
      for (fold in seq_len(inner$n_folds)) {
        eval_rows <- which(inner$fold_id == fold)
        train_rows <- which(inner$fold_id != fold)
        train_keys <- unique(source_key[train_rows])
        eval_keys <- unique(source_key[eval_rows])
        ref_train <- ref_tab[ref_key %in% train_keys, , drop = FALSE]
        ref_eval <- ref_tab[ref_key %in% eval_keys, , drop = FALSE]
        inner_model <- suppressMessages(fit_gaze_replay_model(
          ref_train,
          source_tab[train_rows, , drop = FALSE],
          match_on = match_on,
          contrast_on = NULL,
          refvar = refvar,
          sourcevar = sourcevar,
          spec = spec,
          template_on = template_on
        ))
        for (row in eval_rows) {
          scored <- score_gaze_replay_row(
            source_tab[row, , drop = FALSE],
            ref_eval,
            match_on,
            contrast_on,
            refvar,
            sourcevar,
            inner_model,
            support_tab = source_tab[eval_rows, , drop = FALSE]
          )
          if (evidence_scaled) {
            score_sets[[row]] <- stats::setNames(
              scored$candidates$raw_score, scored$candidates$candidate_key
            )
            evidence_count[[row]] <- scored$evidence_count
          } else {
            score_sets[[row]] <- scored$candidates$log_score
          }
          true_index[[row]] <- which(scored$candidates$is_true)
        }
        fold_audit[[fold]] <- list(
          fold = fold,
          train_rows = train_rows,
          eval_rows = eval_rows,
          train_match_keys = train_keys,
          eval_match_keys = eval_keys,
          overlap_match_n = length(intersect(train_keys, eval_keys))
        )
        if (typicality) {
          # Inner offsets come from the inner training rows only.
          offsets <- replay_typicality(
            inner_model, ref_eval, source_tab[train_rows, , drop = FALSE],
            match_on, contrast_on, refvar, sourcevar
          )
          for (row in eval_rows) {
            score_sets[[row]] <- unlist(gaze_typicality_adjust(
              as.list(score_sets[[row]]), offsets
            ))
          }
          typicality_tables[[fold]] <- cbind(fold = fold, offsets$table)
          fold_audit[[fold]]$typicality <- typicality_tables[[fold]]
        }
      }
      effective_fixations <- vapply(
        source_tab[[sourcevar]],
        function(path) gaze_replay_path_quality(path)$effective_fixations,
        numeric(1)
      )
      if (evidence_scaled) {
        calibration <- fit_gaze_evidence_calibration(
          lapply(score_sets, as.list), true_index, evidence_count,
          control = spec$calibration$control,
          temperature_bounds = spec$temperature_bounds
        )
        calibration$evidence_measure <- "recall_fixations"
        calibration$typicality <- if (typicality) {
          do.call(rbind, typicality_tables)
        }
      } else if (identical(spec$reliability, "effective_fixations")) {
        calibration <- fit_gaze_replay_reliability(
          score_sets,
          true_index,
          effective_fixations = effective_fixations,
          temperature_bounds = spec$temperature_bounds,
          kappa_bounds = spec$reliability_kappa_bounds,
          log_temperature_prior_sd =
            spec$calibration$log_temperature_prior_sd,
          log1p_kappa_prior_sd =
            spec$calibration$log1p_kappa_prior_sd
        )
        reliability_kappa <- calibration$kappa
      } else {
        calibration <- fit_gaze_temperature(
          score_sets,
          true_index,
          bounds = spec$temperature_bounds,
          log_temperature_prior_sd =
            spec$calibration$log_temperature_prior_sd
        )
      }
      calibration$scheme <- if (evidence_scaled) {
        "inner_cross_fitted_evidence_scaled_temperature"
      } else {
        "inner_cross_fitted_candidate_log_loss"
      }
      if (identical(spec$reliability, "effective_fixations")) {
        calibration$scheme <- paste0(
          calibration$scheme,
          "_with_effective_fixation_shrinkage"
        )
      }
      # The evidence-scaled fit keeps its numeric score scale.
      if (evidence_scaled) {
        calibration$score_semantics <- score_scale
      } else {
        calibration$score_scale <- score_scale
      }
      if (legacy) calibration$grid_size <- spec$grid_size
      calibration$folds <- fold_audit
      calibration$seed <- spec$calibration$seed
      temperature <- calibration$temperature
    } else if (evidence_scaled) {
      calibration <- gaze_evidence_calibration_fallback(
        spec$calibration$control, spec$temperature_bounds,
        paste0(
          "fewer than ", 2L * calibration_folds,
          " candidates in at least one training contrast stratum"
        )
      )
      calibration$score_semantics <- score_scale
      calibration$folds <- list()
      calibration$seed <- spec$calibration$seed
      temperature <- calibration$temperature
    } else {
      calibration <- structure(
        list(
          temperature = 1,
          log_loss = NA_real_,
          penalized_objective = NA_real_,
          uncalibrated_log_loss = NA_real_,
          training_n = 0L,
          bounds = spec$temperature_bounds,
          log_temperature_prior_sd =
            spec$calibration$log_temperature_prior_sd,
          at_boundary = FALSE,
          scheme = "identity_fallback",
          score_scale = score_scale,
          grid_size = if (legacy) spec$grid_size,
          reason = paste0(
            "fewer than ", 2L * calibration_folds,
            " candidates in at least one training contrast stratum"
          ),
          folds = list(),
          seed = spec$calibration$seed
        ),
        class = if (identical(spec$reliability, "effective_fixations")) {
          c("gaze_reliability_fit", "list")
        } else {
          c("gaze_temperature_fit", "list")
        }
      )
      if (identical(spec$reliability, "effective_fixations")) {
        calibration$kappa <- 0
        calibration$temperature_only_temperature <- 1
        calibration$temperature_only_log_loss <- NA_real_
        calibration$kappa_bounds <- spec$reliability_kappa_bounds
      }
    }
  }

  structure(
    list(
      spec = spec,
      warp = warp,
      emission_models = emission_models,
      parameters = parameters,
      temperature = temperature,
      reliability_kappa = reliability_kappa,
      calibration = calibration,
      template_on = template_on,
      template_prior = "equal",
      training = list(
        source_n = nrow(source_tab),
        match_keys = source_key,
        transition_candidates = candidates,
        candidate_log_likelihood = candidate_log_likelihood,
        selected_candidate = best,
        template_count = lengths(templates$source_rows),
        em = revision_fit$em,
        background_level = revision_fit$background_level
      ),
      revision = if (legacy) "2026.08" else "2026.10",
      background = revision_fit$background,
      match_on = match_on,
      version = if (!legacy) 5L else if (is.null(template_on) &&
                    identical(spec$reliability, "none")) 3L else 4L
    ),
    class = c("gaze_replay_model", "list")
  )
}

resolve_gaze_replay_group <- function(model, warp_group = NULL) {
  groups <- names(model$emission_models)
  if (is.null(warp_group)) {
    if (length(groups) != 1L) {
      stop("A grouped Replay model requires warp_group.")
    }
    return(groups[[1]])
  }
  if (!warp_group %in% groups) {
    stop("No fitted Replay emission model is available for group '", warp_group, "'.")
  }
  warp_group
}

prepare_gaze_replay_source <- function(source, model, warp_group = NULL,
                                       background_key = NULL,
                                       exclude_key = NULL,
                                       support = NULL) {
  model_revision <- gaze_replay_revision_of(model)
  if (!identical(model_revision, gaze_replay_revision_of(model$spec))) {
    stop("Replay model and spec revisions disagree.")
  }
  group <- resolve_gaze_replay_group(model, warp_group)
  source_measure <- as_gaze_measure(source, model$spec$chronology)
  group_warp <- if (identical(model$warp$type, "none")) {
    model$warp
  } else {
    subset_gaze_warp_model(model$warp, group)
  }
  registered_source <- apply_gaze_warp_model(source_measure, group_warp)
  grid <- if (identical(model$revision, "2026.10")) {
    # One observation per recall fixation; grid_size is not used.
    gaze_replay_prepare_background(
      gaze_replay_fixation_observation(registered_source), model,
      background_key, exclude_key, support
    )
  } else {
    gaze_duration_grid(registered_source, model$spec$grid_size)
  }
  list(
    group = group,
    source = source_measure,
    registered_source = registered_source,
    warp = group_warp,
    grid = grid,
    quality = gaze_replay_path_quality(source)
  )
}

gaze_replay_align_prepared <- function(reference, prepared, model,
                                       candidate_key) {
  reference_measure <- as_gaze_measure(reference, model$spec$chronology)
  if (identical(model$revision, "2026.10")) {
    return(gaze_replay_align_prepared_fixation(
      reference_measure, prepared, model, candidate_key
    ))
  }
  alignment <- gaze_replay_pair_alignment(
    reference_measure,
    prepared$registered_source,
    model$emission_models[[prepared$group]],
    model$parameters,
    model$spec,
    grid = prepared$grid
  )
  alignment$reference <- reference_measure
  alignment$source <- prepared$source
  alignment$registered_source <- prepared$registered_source
  alignment$warp <- prepared$warp
  alignment$spec <- model$spec
  alignment$diagnostics <- c(
    alignment$diagnostics,
    prepared$quality,
    list(
      template_count = 1L,
      template_effective_count = 1,
      template_weight_max = 1
    )
  )

  new_gaze_engine_result(
    engine = "replay",
    candidate_key = candidate_key,
    log_score = alignment$mean_log_score,
    diagnostics = alignment$diagnostics,
    alignment = alignment,
    convergence = alignment$convergence,
    provenance = list(
      engine_version = model$version,
      directionality = "encoding_to_recall",
      score_semantics = "mean_log_likelihood_per_duration_bin",
      raw_score_semantics = "total_duration_grid_log_likelihood",
      raw_log_likelihood = alignment$log_likelihood,
      duration_semantics = paste0(
        "normalized_gaze_time_grid_", model$spec$grid_size
      ),
      candidate_invariant = TRUE,
      warp_group = prepared$group,
      transition_parameters = model$parameters,
      likelihood_temperature = model$temperature,
      temperature_semantics = "residual_scale_on_mean_log_likelihood"
    )
  )
}

#' Align recall gaze to an encoding path with a fitted Replay model
#'
#' @param reference Encoding fixation path.
#' @param source Recall fixation path.
#' @param model A training-only [fit_gaze_replay_model()] result.
#' @param candidate_key Candidate identifier retained in the result.
#' @param warp_group Required fitted group key for grouped models.
#' @param background_key Optional values of the `background_by` columns (in
#'   their declared order) for the recall path; revision `"2026.10"` models
#'   fitted with `background_by` only. `NULL` uses the pooled training
#'   background density.
#'
#' @return A `gaze_engine_result` and a `gaze_replay_alignment` posterior
#'   object. Under revision `"2026.10"` the score is the total trial log
#'   likelihood over recall fixations. Under `"2026.08"` it is the mean log
#'   predictive density per normalized duration bin, and the alignment
#'   retains the raw total HMM log likelihood as a diagnostic.
#' @export
gaze_replay_align <- function(reference, source, model,
                              candidate_key = "candidate", warp_group = NULL,
                              background_key = NULL) {
  if (!inherits(model, "gaze_replay_model")) {
    stop("model must be created by fit_gaze_replay_model().")
  }
  gaze_replay_align_prepared(
    reference,
    prepare_gaze_replay_source(
      source, model, warp_group,
      encode_gaze_replay_background_key(model, background_key)
    ),
    model,
    candidate_key
  )
}

gaze_replay_align_episode_prepared <- function(
    references, prepared, model, candidate_key, template_key) {
  template_quality <- lapply(references, gaze_replay_path_quality)
  component <- lapply(seq_along(references), function(i) {
    gaze_replay_align_prepared(
      references[[i]], prepared, model,
      candidate_key = paste(candidate_key, template_key[[i]], sep = "::")
    )
  })
  component_score <- vapply(component, `[[`, numeric(1), "log_score")
  mixture <- gaze_replay_log_mixture(component_score)
  modal <- which.max(mixture$posterior_weight)
  alignment <- component[[modal]]$alignment
  scalar_diagnostics <- c(
    "replay_coverage", "background_coverage", "expected_restarts",
    "restart_rate", "spatial_rmse"
  )
  diagnostics <- lapply(scalar_diagnostics, function(name) {
    sum(mixture$posterior_weight * vapply(
      component, function(value) value$diagnostics[[name]], numeric(1)
    ))
  })
  names(diagnostics) <- scalar_diagnostics
  positive <- mixture$posterior_weight > 0
  template_entropy <- -sum(
    mixture$posterior_weight[positive] *
      log(mixture$posterior_weight[positive])
  )
  diagnostics <- c(
    diagnostics,
    prepared$quality,
    list(
      template_count = as.integer(length(references)),
      template_effective_count = exp(template_entropy),
      template_weight_max = max(mixture$posterior_weight),
      modal_template = as.character(template_key[[modal]])
    )
  )
  alignment$components <- lapply(component, `[[`, "alignment")
  alignment$component_log_score <- component_score
  alignment$template_key <- as.character(template_key)
  alignment$template_prior <- mixture$prior_weight
  alignment$template_posterior <- mixture$posterior_weight
  alignment$template_count <- as.integer(length(references))
  alignment$modal_template <- as.character(template_key[[modal]])
  alignment$episode_log_score <- mixture$log_score
  alignment$template_quality <- template_quality
  alignment$diagnostics <- diagnostics
  class(alignment) <- c(
    "gaze_replay_episode_alignment", "gaze_replay_alignment", "list"
  )

  fixation_level <- identical(model$revision, "2026.10")
  new_gaze_engine_result(
    engine = "replay",
    candidate_key = candidate_key,
    log_score = mixture$log_score,
    diagnostics = diagnostics,
    alignment = alignment,
    convergence = list(
      converged = all(vapply(
        component, function(value) value$convergence$converged, logical(1)
      )),
      method = "separate_template_mixture",
      component_count = length(component)
    ),
    provenance = list(
      engine_version = model$version,
      directionality = "encoding_to_recall",
      score_semantics = if (fixation_level) {
        "equal_mixture_of_total_trial_log_likelihood"
      } else {
        "equal_mixture_of_mean_log_likelihood_per_duration_bin"
      },
      raw_score_semantics = "separate_component_hmm_likelihoods",
      duration_semantics = if (fixation_level) {
        "fixation_level_log_normal_duration_emissions"
      } else {
        paste0("normalized_gaze_time_grid_", model$spec$grid_size)
      },
      candidate_invariant = TRUE,
      template_prior = "equal",
      template_count = length(component),
      no_cross_template_transitions = TRUE,
      likelihood_temperature = model$temperature
    )
  )
}

#' Align recall gaze to a mixture of encoding presentations
#'
#' Each encoding path is aligned independently. Their scores (total log
#' likelihoods under revision `"2026.10"`, mean log likelihoods per duration
#' bin under `"2026.08"`) are combined as an equal-weight mixture, so no
#' transition is created between study presentations. The returned alignment retains all component
#' posteriors and uses the highest-responsibility component for the ordinary
#' overlay and braid fields.
#'
#' @param references A list of encoding fixation paths for one candidate item.
#' @param source One recall fixation path.
#' @param model A training-only [fit_gaze_replay_model()] result.
#' @param candidate_key Candidate identifier retained in the result.
#' @param template_key Optional unique identifiers for `references`.
#' @param warp_group Required fitted group key for grouped models.
#' @param background_key Optional values of the `background_by` columns (in
#'   their declared order) for the recall path; revision `"2026.10"` models
#'   fitted with `background_by` only. `NULL` uses the pooled training
#'   background density.
#'
#' @return A `gaze_engine_result` whose alignment inherits from
#'   `gaze_replay_episode_alignment` and `gaze_replay_alignment`.
#' @export
gaze_replay_align_episode <- function(
    references, source, model, candidate_key = "candidate",
    template_key = NULL, warp_group = NULL, background_key = NULL) {
  if (!inherits(model, "gaze_replay_model")) {
    stop("model must be created by fit_gaze_replay_model().")
  }
  if (!is.list(references) || length(references) < 1L) {
    stop("references must contain at least one encoding fixation path.")
  }
  if (is.null(template_key)) template_key <- seq_along(references)
  if (length(template_key) != length(references) || anyNA(template_key) ||
      anyDuplicated(as.character(template_key))) {
    stop("template_key must contain one complete unique value per reference.")
  }
  gaze_replay_align_episode_prepared(
    references,
    prepare_gaze_replay_source(
      source, model, warp_group,
      encode_gaze_replay_background_key(model, background_key)
    ),
    model,
    candidate_key,
    template_key
  )
}

score_gaze_replay_row <- function(source_row, ref_eval, match_on, contrast_on,
                                  refvar, sourcevar, model,
                                  support_tab = NULL, typicality = NULL) {
  source_match_key <- gaze_key(source_row, match_on, "match_on")
  ref_match_key <- gaze_key(ref_eval, match_on, "match_on")
  source_contrast_key <- if (is.null(contrast_on)) "all" else
    gaze_key(source_row, contrast_on, "contrast_on")
  ref_contrast_key <- if (is.null(contrast_on)) rep("all", nrow(ref_eval)) else
    gaze_key(ref_eval, contrast_on, "contrast_on")
  candidate_rows <- which(ref_contrast_key == source_contrast_key)
  candidate_key <- unique(ref_match_key[candidate_rows])
  true_candidate <- match(source_match_key, candidate_key)
  if (is.na(true_candidate) || length(candidate_key) < 2L) {
    stop("Each Replay row requires one true candidate and at least one nonmatch.")
  }
  warp_group <- if (is.null(model$spec$warp$fit_by)) {
    names(model$emission_models)[[1]]
  } else {
    gaze_key(source_row, model$spec$warp$fit_by, "warp fit_by")
  }
  background_key <- NULL
  exclude_key <- NULL
  if (identical(model$revision, "2026.10")) {
    if (!is.null(model$background$background_by)) {
      background_key <- gaze_key(
        source_row, model$background$background_by, "background_by"
      )
    }
    # Exclude every candidate item, never only the true one: otherwise the
    # shared background would dip at the true item's locations.
    exclude_key <- unique(gaze_key(
      ref_eval[candidate_rows, , drop = FALSE],
      model$background$exclude_on, "background exclusion"
    ))
  }
  support <- if (identical(model$revision, "2026.10")) {
    gaze_replay_support_table(model, support_tab, sourcevar, background_key)
  } else {
    NULL
  }
  prepared <- prepare_gaze_replay_source(
    source_row[[sourcevar]][[1]], model, warp_group,
    background_key, exclude_key, support
  )
  engine_results <- lapply(candidate_key, function(key) {
    rows <- candidate_rows[ref_match_key[candidate_rows] == key]
    template_key <- if (is.null(model$template_on)) {
      "template"
    } else {
      replay_template_labels(
        ref_eval[rows, , drop = FALSE], model$template_on
      )
    }
    gaze_replay_align_episode_prepared(
      ref_eval[[refvar]][rows],
      prepared,
      model,
      candidate_key = key,
      template_key = template_key
    )
  })
  quality <- prepared$quality
  reliability <- if (identical(
    model$spec$reliability, "effective_fixations"
  )) {
    gaze_replay_reliability(
      quality$effective_fixations, model$reliability_kappa
    )
  } else {
    1
  }
  evidence_scaled <- identical(model$revision, "2026.10") &&
    gaze_calibration_evidence_scaled(model$spec)
  evidence_count <- if (identical(model$revision, "2026.10")) {
    as.numeric(prepared$grid$n_fixations)
  } else {
    NA_real_
  }
  raw_score <- vapply(engine_results, `[[`, numeric(1), "log_score")
  offset <- rep(0, length(candidate_key))
  scale <- rep(1, length(candidate_key))
  ranking_score <- raw_score
  if (evidence_scaled) {
    if (!is.null(typicality)) {
      offset <- unlist(typicality$offsets[candidate_key], use.names = FALSE)
      if (!is.null(typicality$scale)) {
        scale <- unname(typicality$scale[candidate_key])
      }
      ranking_score <- unlist(gaze_typicality_adjust(
        stats::setNames(as.list(raw_score), candidate_key), typicality
      ), use.names = FALSE)
    }
    calibration <- model$calibration
    if (!inherits(calibration, "gaze_evidence_calibration")) {
      calibration <- gaze_replay_identity_calibration()
    }
    evidence <- score_gaze_calibrated_row(
      as.list(ranking_score), true_candidate, evidence_count,
      calibration, candidate_key = candidate_key,
      candidate_pool_id = paste0("held-out:", source_contrast_key)
    )
  } else {
    evidence <- score_gaze_engine_results(
      engine_results,
      true_key = source_match_key,
      temperature = model$temperature,
      reliability = reliability,
      candidate_pool_id = paste0("held-out:", source_contrast_key)
    )
    if (identical(model$revision, "2026.10")) {
      # Rank and top-1 never depend on the calibration under 2026.10.
      evidence <- gaze_apply_reference_rank(evidence, raw_score,
                                            true_candidate)
    }
  }
  first_row <- vapply(candidate_key, function(key) {
    candidate_rows[which(ref_match_key[candidate_rows] == key)[[1L]]]
  }, integer(1))
  candidate_table <- ref_eval[
    first_row, unique(c(match_on, contrast_on)), drop = FALSE
  ]
  candidate_table$log_score <- if (evidence_scaled) {
    raw_score
  } else {
    evidence$candidates$log_score
  }
  if (evidence_scaled) {
    candidate_table$candidate_key <- candidate_key
    candidate_table$raw_score <- raw_score
    candidate_table$typicality_offset <- offset
    candidate_table$typicality_scale <- scale
    candidate_table$ranking_score <- ranking_score
    candidate_table$calibrated_logit <- evidence$candidates$log_score
  }
  candidate_table$prior <- evidence$candidates$prior
  candidate_table$base_posterior <- evidence$candidates$base_posterior
  candidate_table$posterior <- evidence$candidates$posterior
  candidate_table$is_true <- evidence$candidates$is_true
  candidate_table$template_count <- vapply(
    candidate_key,
    function(key) sum(ref_match_key[candidate_rows] == key),
    integer(1)
  )
  alignment <- engine_results[[true_candidate]]$alignment
  alignment$diagnostics$reliability_weight <- reliability
  alignment$diagnostics$reliability_kappa <- model$reliability_kappa
  candidate_components <- dplyr::bind_rows(lapply(
    seq_along(engine_results), function(i) {
      component_alignment <- engine_results[[i]]$alignment
      data.frame(
        candidate_key = candidate_key[[i]],
        template_key = component_alignment$template_key,
        template_log_score = component_alignment$component_log_score,
        template_prior = component_alignment$template_prior,
        template_posterior = component_alignment$template_posterior,
        template_raw_fixation_count = vapply(
          component_alignment$template_quality,
          `[[`, integer(1), "raw_fixation_count"
        ),
        template_coalesced_fixation_count = vapply(
          component_alignment$template_quality,
          `[[`, integer(1), "coalesced_fixation_count"
        ),
        template_effective_fixations = vapply(
          component_alignment$template_quality,
          `[[`, numeric(1), "effective_fixations"
        ),
        template_total_duration = vapply(
          component_alignment$template_quality,
          `[[`, numeric(1), "total_duration"
        ),
        stringsAsFactors = FALSE
      )
    }
  ))

  list(
    evidence = evidence,
    alignment = alignment,
    candidates = candidate_table,
    candidate_components = candidate_components,
    quality = quality,
    background_level = prepared$grid$background_level,
    evidence_count = evidence_count,
    all_converged = all(vapply(engine_results, function(result) {
      result$convergence$converged
    }, logical(1)))
  )
}

# Temperature one, no evidence scaling: used by revision 2026.10 models
# fitted without a contrastive calibration set (as before A3).
gaze_replay_identity_calibration <- function() {
  structure(
    list(inverse_temperature = 1, temperature = 1, gamma = 0,
         evidence_reference = 1, scheme = "identity_no_calibration_set"),
    class = c("gaze_evidence_calibration", "list")
  )
}

# Typicality offsets for Replay (revision 2026.10, plan A3): each candidate's
# mean total log likelihood against a fixed seeded subsample of training
# recalls of other items. Each source's background excludes the candidate
# pool (as for scored rows) and the source's own item, so a training recall
# never explains itself through the background.
replay_typicality <- function(model, ref_eval, train_source, match_on,
                              contrast_on, refvar, sourcevar) {
  spec <- model$spec
  control <- spec$calibration$control
  item_on <- gaze_typicality_item_on(control, match_on, contrast_on)
  ref_key <- gaze_key(ref_eval, match_on, "match_on")
  ref_item <- gaze_key(ref_eval, item_on, "typicality item")
  ref_contrast <- if (is.null(contrast_on)) {
    rep("all", nrow(ref_eval))
  } else {
    gaze_key(ref_eval, contrast_on, "contrast_on")
  }
  train_item <- gaze_key(train_source, item_on, "typicality item")
  source_rows <- gaze_typicality_source_rows(
    train_item, control$typicality_sources, spec$calibration$seed
  )
  sources <- train_source[source_rows, , drop = FALSE]
  source_item <- train_item[source_rows]
  exclude_on <- model$background$exclude_on
  source_exclude <- gaze_key(sources, exclude_on, "background exclusion")
  keys <- unique(ref_key)
  score_matrix <- matrix(NA_real_, length(keys), nrow(sources))
  for (pool in unique(ref_contrast)) {
    pool_rows <- which(ref_contrast == pool)
    pool_keys <- unique(ref_key[pool_rows])
    pool_exclude <- unique(gaze_key(
      ref_eval[pool_rows, , drop = FALSE], exclude_on, "background exclusion"
    ))
    for (j in seq_len(nrow(sources))) {
      eligible <- pool_keys[vapply(pool_keys, function(key) {
        !source_item[[j]] %in% ref_item[ref_key == key]
      }, logical(1))]
      if (!length(eligible)) next
      source_row <- sources[j, , drop = FALSE]
      warp_group <- if (is.null(spec$warp$fit_by)) {
        names(model$emission_models)[[1]]
      } else {
        gaze_key(source_row, spec$warp$fit_by, "warp fit_by")
      }
      background_key <- if (is.null(model$background$background_by)) {
        NULL
      } else {
        gaze_key(source_row, model$background$background_by, "background_by")
      }
      prepared <- prepare_gaze_replay_source(
        source_row[[sourcevar]][[1]], model, warp_group, background_key,
        union(pool_exclude, source_exclude[[j]])
      )
      for (key in eligible) {
        rows <- pool_rows[ref_key[pool_rows] == key]
        template_key <- if (is.null(model$template_on)) {
          "template"
        } else {
          replay_template_labels(ref_eval[rows, , drop = FALSE],
                                 model$template_on)
        }
        score_matrix[match(key, keys), j] <- gaze_replay_align_episode_prepared(
          ref_eval[[refvar]][rows], prepared, model,
          candidate_key = key, template_key = template_key
        )$log_score
      }
    }
  }
  table <- gaze_typicality_summary(score_matrix, keys)
  list(
    offsets = stats::setNames(as.list(table$offset), keys),
    scale = if (gaze_calibration_standardized(spec)) {
      stats::setNames(table$scale, keys)
    },
    grand = table$grand_mean[[1L]],
    table = table,
    item_on = item_on
  )
}

#' Cross-fitted directional GazeWeave Replay analysis
#'
#' Fits warp, background, emission, and transition parameters on training
#' items, then scores every held-out source path against its permitted encoding
#' candidates.
#'
#' @inheritParams gaze_weave_cv
#' @param spec A [gaze_replay_spec()].
#' @param template_on Optional columns identifying separate encoding
#'   presentations within each matched episode. See
#'   [fit_gaze_replay_model()].
#'
#' @return A `gaze_replay_fit` with `gaze_info_bits` as its primary endpoint.
#' @export
gaze_replay_cv <- function(ref_tab, source_tab, match_on,
                           contrast_on = NULL,
                           refvar = "fixgroup", sourcevar = "fixgroup",
                           spec = gaze_replay_spec(), split_on = match_on,
                           n_folds = NULL, seed = 1,
                           fit_source_filter = NULL,
                           eval_source_filter = NULL,
                           template_on = NULL) {
  if (!inherits(spec, "gaze_replay_spec")) {
    stop("spec must be created by gaze_replay_spec().")
  }
  required_ref <- unique(c(
    match_on, contrast_on, template_on, spec$warp$fit_by, refvar
  ))
  required_source <- unique(c(
    match_on, contrast_on, split_on, spec$warp$fit_by, spec$background_by,
    sourcevar
  ))
  if (!all(required_ref %in% names(ref_tab)) ||
      !all(required_source %in% names(source_tab))) {
    stop("Replay matching, split, warp, and fixation columns must exist.")
  }
  ref_match_key <- gaze_key(ref_tab, match_on, "match_on")
  replay_template_structure(ref_tab, source_tab, match_on, template_on)
  source_tab <- dplyr::ungroup(source_tab)
  source_tab[["..gaze_row_id"]] <- seq_len(nrow(source_tab))
  source_match_key <- gaze_key(source_tab, match_on, "match_on")
  if (any(!source_match_key %in% ref_match_key)) {
    stop("Every Replay source match_on key must exist in ref_tab.")
  }
  fit_mask <- resolve_gaze_weave_filter(source_tab, fit_source_filter, "fit_source_filter")
  eval_mask <- resolve_gaze_weave_filter(source_tab, eval_source_filter, "eval_source_filter")
  folds <- make_gaze_weave_candidate_folds(
    source_tab, split_on, contrast_on, n_folds, seed, match_on, eval_mask
  )

  fold_results <- vector("list", folds$n_folds)
  fold_info <- vector("list", folds$n_folds)
  revision_2026_10 <- !gaze_replay_is_legacy(spec)
  if (revision_2026_10) note_gaze_replay_plane(spec)
  evidence_scaled <- revision_2026_10 && gaze_calibration_evidence_scaled(spec)
  typicality <- revision_2026_10 && gaze_calibration_typicality(spec)
  if (typicality) {
    item_on <- gaze_typicality_item_on(
      spec$calibration$control, match_on, contrast_on
    )
    if (!all(item_on %in% names(ref_tab)) ||
        !all(item_on %in% names(source_tab))) {
      stop("Typicality item columns must exist in both tables.")
    }
  }
  training_fallback_n <- 0L
  unseen_level_n <- 0L
  for (fold in seq_len(folds$n_folds)) {
    eval_rows <- which(folds$fold_id == fold & eval_mask)
    if (length(eval_rows) == 0L) next
    eval_source <- source_tab[eval_rows, , drop = FALSE]
    eval_keys <- unique(gaze_key(eval_source, match_on, "match_on"))
    train_candidates <- which(folds$fold_id != fold & fit_mask)
    train_key_all <- gaze_key(source_tab[train_candidates, , drop = FALSE],
                              match_on, "match_on")
    train_rows <- train_candidates[!train_key_all %in% eval_keys]
    train_source <- source_tab[train_rows, , drop = FALSE]
    train_keys <- unique(gaze_key(train_source, match_on, "match_on"))
    ref_train <- ref_tab[ref_match_key %in% train_keys, , drop = FALSE]
    ref_eval <- ref_tab[ref_match_key %in% eval_keys, , drop = FALSE]
    if (nrow(train_source) == 0L || nrow(ref_train) == 0L) {
      stop("Fold ", fold, " has no Replay training data.")
    }
    model <- if (revision_2026_10) {
      suppressMessages(fit_gaze_replay_model(
        ref_train, train_source, match_on, contrast_on, refvar, sourcevar,
        spec, template_on = template_on
      ))
    } else {
      fit_gaze_replay_model(
        ref_train, train_source, match_on, contrast_on, refvar, sourcevar,
        spec, template_on = template_on
      )
    }
    if (revision_2026_10) {
      training_fallback_n <- training_fallback_n +
        sum(model$training$background_level != "participant")
      if (!is.null(spec$background_by)) {
        unseen_level_n <- unseen_level_n + sum(!gaze_key(
          eval_source, spec$background_by, "background_by"
        ) %in% gaze_key(train_source, spec$background_by, "background_by"))
      }
    }
    typicality_fold <- if (typicality) {
      replay_typicality(model, ref_eval, train_source, match_on, contrast_on,
                        refvar, sourcevar)
    }
    scored <- lapply(seq_len(nrow(eval_source)), function(i) {
      score_gaze_replay_row(
        eval_source[i, , drop = FALSE], ref_eval, match_on, contrast_on,
        refvar, sourcevar, model, support_tab = eval_source,
        typicality = typicality_fold
      )
    })
    result_fold <- eval_source
    result_fold$.cv_fold <- fold
    if (evidence_scaled) {
      result_fold$temperature <- vapply(scored, function(result) {
        result$evidence$temperature
      }, numeric(1))
      result_fold$inverse_temperature <- vapply(scored, function(result) {
        result$evidence$inverse_temperature
      }, numeric(1))
      result_fold$evidence_count <- vapply(
        scored, `[[`, numeric(1), "evidence_count"
      )
    }
    for (field in c(
      "gaze_info_bits", "base_gaze_info_bits", "odds_bits",
      "posterior_true", "log_loss", "base_log_loss", "brier_score",
      "template_rank", "top1_credit", "candidate_count", "reliability"
    )) {
      result_fold[[field]] <- vapply(scored, function(result) {
        result$evidence[[field]]
      }, numeric(1))
    }
    result_fold$candidate_count <- as.integer(result_fold$candidate_count)
    result_fold$raw_fixation_count <- vapply(
      scored, function(result) result$quality$raw_fixation_count, integer(1)
    )
    result_fold$coalesced_fixation_count <- vapply(
      scored,
      function(result) result$quality$coalesced_fixation_count,
      integer(1)
    )
    for (field in c(
      "effective_fixations", "total_duration", "duration_concentration",
      "spatial_dispersion"
    )) {
      result_fold[[field]] <- vapply(
        scored, function(result) result$quality[[field]], numeric(1)
      )
    }
    result_fold$all_converged <- vapply(scored, `[[`, logical(1), "all_converged")
    if (revision_2026_10) {
      result_fold$background_level <- vapply(
        scored, `[[`, character(1), "background_level"
      )
    }
    result_fold$alignment <- lapply(scored, `[[`, "alignment")
    result_fold$candidates <- lapply(scored, `[[`, "candidates")
    fold_results[[fold]] <- result_fold
    fold_info[[fold]] <- list(
      fold = fold,
      train_rows = train_rows,
      eval_rows = eval_rows,
      train_match_keys = train_keys,
      eval_match_keys = eval_keys,
      overlap_match_n = length(intersect(train_keys, eval_keys)),
      transition_parameters = model$parameters,
      calibration = model$calibration,
      template_on = template_on,
      template_count = model$training$template_count,
      emission_models = model$emission_models,
      warp = model$warp$info
    )
    if (typicality) {
      fold_info[[fold]]$typicality <- cbind(fold = fold, typicality_fold$table)
    }
  }

  results <- dplyr::bind_rows(fold_results)
  if (nrow(results) == 0L) {
    stop("No held-out Replay rows were scored.")
  }
  results <- results[order(results[["..gaze_row_id"]]), , drop = FALSE]
  results[["..gaze_row_id"]] <- NULL
  background_fallback <- NULL
  if (revision_2026_10) {
    background_fallback <- list(
      background_by = spec$background_by,
      background_support = spec$background_support,
      training_rows = as.integer(training_fallback_n),
      scored_rows = as.integer(sum(!results$background_level %in%
                                     c("participant", "held_out_support"))),
      unseen_level_rows = as.integer(unseen_level_n)
    )
    if (unseen_level_n > 0L &&
        identical(spec$background_support, "training")) {
      message(
        "Replay: ", unseen_level_n, " scored rows belong to background_by ",
        "levels absent from their training fold (e.g. held-out ",
        "participants); they use the population background. ",
        "background_support = \"held_out\" cannot help here: it needs an ",
        "item-level split and a contrast_on that blocks items, so that ",
        "non-candidate recalls of the same participant share the evaluation ",
        "fold."
      )
    }
    if (!is.null(spec$background_by) &&
        background_fallback$scored_rows + training_fallback_n > 0L) {
      message(
        "Replay: the pooled background replaced the participant-level ",
        "background for ", background_fallback$scored_rows, " of ",
        nrow(results), " scored rows and ", training_fallback_n,
        " training rows (summed over folds)."
      )
    }
  }
  provenance <- list(
    engine = "replay",
    primary_score = "gaze_info_bits",
    candidate_prior = "uniform within held-out candidate set",
    temperature = "outer-training residual temperature on mean log likelihood per duration bin",
    score_semantics = "mean_log_likelihood_per_duration_bin",
    template_on = template_on,
    template_prior = if (is.null(template_on)) "single" else "equal",
    reliability = spec$reliability,
    revision = if (is.null(spec$revision)) "2026.08" else spec$revision,
    background_fallback = background_fallback,
    # Frozen 2026.08 layout: this element is present and NULL.
    repeated_grid_rows = NULL,
    seed = seed,
    n_folds = folds$n_folds
  )
  if (revision_2026_10) {
    provenance$temperature <-
      "outer-training residual temperature on total trial log likelihood"
    provenance$score_semantics <- "total_trial_log_likelihood"
    provenance$repeated_grid_rows <- NULL
    provenance$observation_unit <- "recall_fixation"
  }
  calibration_summary <- NULL
  if (evidence_scaled) {
    provenance$temperature <- paste0(
      "inner out-of-fold evidence-scaled temperature (recall fixations) ",
      "on total trial log likelihood",
      if (typicality) paste0(" with ", spec$calibration$control$typicality, " typicality offset") else ""
    )
    if (typicality) {
      provenance$score_semantics <- paste0(
        "total_trial_log_likelihood_typicality_adjusted",
        "(ranking_score_not_normalised_likelihood)"
      )
    }
    calibration_summary <- c(
      list(heldout_log_loss = mean(results$log_loss)),
      gaze_calibration_fit_summary(fold_info, results, typicality)
    )
  }
  fit <- structure(
    list(
      results = results,
      spec = spec,
      folds = fold_info,
      keys = list(
        match_on = match_on,
        contrast_on = contrast_on,
        split_on = split_on,
        id_columns = unique(c(match_on, contrast_on, split_on))
      ),
      provenance = provenance
    ),
    class = c("gaze_replay_fit", "list")
  )
  # Earlier layouts have no calibration element.
  if (!is.null(calibration_summary)) fit$calibration <- calibration_summary
  fit
}

#' @export
print.gaze_replay_fit <- function(x, ...) {
  cat("Cross-fitted GazeWeave Replay analysis\n")
  cat("  rows:", nrow(x$results), "\n")
  cat("  folds:", x$provenance$n_folds, "\n")
  cat("  mean gaze_info_bits:",
      signif(mean(x$results$gaze_info_bits, na.rm = TRUE), 5), "\n")
  invisible(x)
}

#' Tidy GazeWeave Replay results
#'
#' @param x A `gaze_replay_fit`.
#' @param diagnostics Include calibration, rank, convergence, and fold columns.
#' @param ... Unused.
#'
#' @return A tibble with identifiers and held-out `gaze_info_bits`.
#' @export
tidy.gaze_replay_fit <- function(x, diagnostics = FALSE, ...) {
  columns <- unique(c(x$keys$id_columns, "gaze_info_bits"))
  if (isTRUE(diagnostics)) {
    columns <- unique(c(
      columns, "odds_bits", "posterior_true", "log_loss", "brier_score",
      "base_gaze_info_bits", "base_log_loss", "reliability",
      "template_rank", "top1_credit", "candidate_count", "all_converged",
      "raw_fixation_count", "coalesced_fixation_count",
      "effective_fixations", "total_duration", "duration_concentration",
      "spatial_dispersion", ".cv_fold"
    ))
  }
  tibble::as_tibble(x$results[, columns, drop = FALSE])
}
