# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

transport_v3_stationarity_native_cpp <- function(augmented, centered_gradient, entropy) {
    .Call(`_eyesim_transport_v3_stationarity_native_cpp`, augmented, centered_gradient, entropy)
}

transport_v3_profile_native_cpp <- function(reference_mass, source_mass, reference_relation, source_relation, spatial_cost, coverage_values, entropy_schedule, temporal_weight, selection_weight, maxit, step_size, tolerance, projection_maxit, projection_tolerance, revision = 0L, chronology_pseudo_count = 0.0, multistart = 1L) {
    .Call(`_eyesim_transport_v3_profile_native_cpp`, reference_mass, source_mass, reference_relation, source_relation, spatial_cost, coverage_values, entropy_schedule, temporal_weight, selection_weight, maxit, step_size, tolerance, projection_maxit, projection_tolerance, revision, chronology_pseudo_count, multistart)
}

